FROM openjdk:8-jdk-slim
MAINTAINER Kubernauts-lab
		
ARG JMETER_VERSION=5.0
		
RUN apt-get clean && \
apt-get update && \
apt-get -qy install \
wget \
telnet \
iputils-ping \
unzip
RUN   mkdir /jmeter \
&& cd /jmeter/ \
&& wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
&& tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
&& rm apache-jmeter-$JMETER_VERSION.tgz

ADD https://github.com/raladev/load/blob/master/JARs/pepper-box-1.0.jar?raw=true /jmeter/apache-jmeter-$JMETER_VERSION/lib/ext/pepper-box-1.0.jar

RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && wget -q -O /tmp/bzm-parallel-0.7.zip https://jmeter-plugins.org/files/packages/bzm-parallel-0.7.zip && unzip -n /tmp/bzm-parallel-0.7.zip && rm /tmp/bzm-parallel-0.7.zip

COPY plugins/JMeterPlugins-Standard-1.4.0.zip /tmp/
RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && unzip -n /tmp/JMeterPlugins-Standard-1.4.0.zip && rm /tmp/JMeterPlugins-Standard-1.4.0.zip

ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION/
		
ENV PATH $JMETER_HOME/bin:$PATH
