import java.text.SimpleDateFormat 

long elapsedTimeInMs = System.currentTimeMillis() - Long.parseLong(props.get('START.MS'))
def elapsedTime = new SimpleDateFormat("mm:ss:SSS").format(elapsedTimeInMs)

if(props.write_a_message_toggle.toBoolean()){
    println "Std-Out message generated by a groovy sampler. Test Elapsed Time: $elapsedTime"
    log.info "Log.Info message generated by a groovy sampler. Test Elapsed Time: $elapsedTime"
}
